worker_processes 1;
events { worker_connections 1024; }
http {
    server {
        listen unix:/var/run/bench/nginx/entry.sock;

        location /builtin/health {
            return 200 "Hello from Nginx built-in";
        }

        location /proxy/ {
            proxy_pass http://unix:/var/run/bench/backends/nginx/backend-service/node-0.sock:/;
        }
    }

    server {
        listen 8443 ssl;
        ssl_certificate     /etc/nginx/tls/cert.pem;
        ssl_certificate_key /etc/nginx/tls/key.pem;

        location / {
            proxy_pass http://unix:/var/run/nautrouds/entrypoints/nautrouds-0.sock:/;
        }
    }

    server {
        listen 8444 ssl;
        ssl_certificate     /etc/nginx/tls/cert.pem;
        ssl_certificate_key /etc/nginx/tls/key.pem;

        location / {
            proxy_pass http://unix:/var/run/bench/backends/nginx/backend-service/node-0.sock:/;
        }
    }
}
